# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "^tests/unit/umbrella/.+"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.3.1"
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/hadialqattan/pycln
  rev: "v2.1.3"
  hooks:
  - id: pycln

- repo: https://github.com/psf/black
  rev: "22.12.0"
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: "5.11.4"
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: "6.0.0"
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.991"
  hooks:
  - id: mypy
    files: ^raincoat/
    args: []
    additional_dependencies:
      - "types-colorama==0.4.15"
      - "types-requests==2.28.11.2"
      - "types-click==7.1.8"
      - "asttokens==2.0.8"
      - "importlib_metadata==5.0.0"


- repo: https://github.com/PyCQA/doc8
  rev: "v1.1.1"
  hooks:
  - id: doc8

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 0.4.0
  hooks:
    - id: sync_with_poetry
