#!/usr/bin/env bash

COVERAGE_FLAGS="--cov=raincoat --cov-report xml --cov-report term --cov-report html --cov-config .coveragerc"

if [ -z ${COVERAGE+x} ];
	then
	COVERAGE_FLAGS=""
fi

pytest -v $COVERAGE_FLAGS tests/
