#!/usr/bin/env bash

COVERAGE_FLAGS="--cov=raincoat --cov-report xml --cov-report term --cov-report html"

TESTS="acceptance_tests/"

if [ -z ${COVERAGE+x} ];
    then
    COVERAGE_FLAGS=""
fi


if [ -z ${ACCEPTANCE+x} ];
    then
    TESTS="tests/"
fi

pytest -v $COVERAGE_FLAGS $TESTS
